linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  govet:
    enable-all: true
    disable:
      - fieldalignment
  gocritic:
    enabled-checks:
      - appendAssign
      - argOrder
      - badCond
      - caseOrder
      - codegenComment
      - defaultCaseOrder
      - dupArg
      - dupBranchBody
      - dupCase
      - dupSubExpr
      - emptyFallthrough
      - emptyStringTest
      - exitAfterDefer
      - indexAlloc
      - mapKey
      - nilValReturn
      - stringsCompare
      - weakcond

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - typecheck
    - gocritic
    - gofmt
    - revive

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec

run:
  timeout: 5m
